### PR TITLE
Create Ankush_Chauhan.md

### PR DESCRIPTION
**Pull request by ankushchk**
**@Isha2103  please review and merge**

### CODE REVIEW

**Review by Isha2103 — CHANGES_REQUESTED** [review]
Please follow the same snippet of information as given in Readme.md.
No need to add whole info:)

**Comment by An-prog-hub** [comment]
**Sure I will do the same**

**Comment by An-prog-hub** [comment]
@Isha2103  I just update it 
https://static.skaip.org/img/emoticons/180x180/f6fcff/highfive.gif

**Comment by ankushchk** [comment]
**@Isha2103 I just update it**

**Comment by An-prog-hub** [comment]
**@Isha2103 merge it**

**Pull request closed without merging**
